maps:
  lobby:
    locationspawnnpcstartgame:
      villager:
        x: -815.5
        y: 55
        z: -760.5
  map:
    location:
      mine:
        supermine:
          loc:
            x: 147.5
            y: 90
            z: 107.5
          zone:
            '1':
              x: 129
              y: 89
              z: 100
            '2':
              x: 142
              y: 78
              z: 114
        base:
          zone:
            red:
              '1':
                x: 101
                y: 122
                z: 69
              '2':
                x: 44
                y: 93
                z: 23
            green:
              '1':
                x: 101
                y: 122
                z: 184
              '2':
                x: 44
                y: 93
                z: 138
            cyan:
              '1':
                x: 226
                y: 122
                z: 68
              '2':
                x: 169
                y: 93
                z: 22
            purple:
              '1':
                x: 226
                y: 122
                z: 183
              '2':
                x: 169
                y: 93
                z: 137
      armorstand:
        '1':
          x: 83.7
          y: 124.28
          z: 46.14
        '2':
          x: 209.32
          y: 124.28
          z: 44.96
        '3':
          x: 208.9
          y: 124.28
          z: 160.14
        '4':
          x: 84.24
          y: 124.28
          z: 160.84
      lighthouse:
        red:
          x: 65
          y: 127
          z: 46
        cyan:
          x: 190
          y: 127
          z: 45
        green:
          x: 65
          y: 127
          z: 161
        purple:
          x: 190
          y: 127.0
          z: 160.03
      mob:
        spawnlocation:
          red:
            '1':
              x: 73.63
              y: 124.0
              z: 60.21
            '2':
              x: 59.65
              y: 124.0
              z: 60.38
            '3':
              x: 51.79
              y: 124.0
              z: 52.58
            '4':
              x: 51.53
              y: 124.0
              z: 39.32
            '5':
              x: 59.6
              y: 124.0
              z: 31.65
            '6':
              x: 72.81
              y: 124.0
              z: 31.82
          cyan:
            '1':
              x: 196.74
              y: 124.5
              z: 30.08
            '2':
              x: 184.27
              y: 124.0
              z: 30.62
            '3':
              x: 176.69
              y: 124.0
              z: 38.71
            '4':
              x: 176.48
              y: 124.0
              z: 51.89
            '5':
              x: 184.01
              y: 124.5
              z: 59.72
            '6':
              x: 197.36
              y: 124.0
              z: 59.42
          purple:
            '1':
              x: 197.85
              y: 124.0
              z: 145.63
            '2':
              x: 184.72
              y: 124.0
              z: 145.8
            '3':
              x: 176.55
              y: 124.0
              z: 154.0
            '4':
              x: 176.41
              y: 124.0
              z: 166.32
            '5':
              x: 184.86
              y: 124.0
              z: 174.68
            '6':
              x: 197.78
              y: 124.0
              z: 174.09
          green:
            '1':
              x: 71.74
              y: 124.5
              z: 175.71
            '2':
              x: 59.61
              y: 124.5
              z: 175.76
            '3':
              x: 51.49
              y: 124.0
              z: 166.92
            '4':
              x: 51.56
              y: 124.0
              z: 154.83
            '5':
              x: 59.5
              y: 124.0
              z: 146.59
            '6':
              x: 72.92
              y: 124.5
              z: 146.26
      baseteleportsign:
        x: 149
        y: 91
        z: 107
      signteleportsupersign:
        '1':
          x: 174
          y: 125
          z: 45
        '2':
          x: 174
          y: 125
          z: 44
        '3':
          x: 49
          y: 125
          z: 46
        '4':
          x: 49
          y: 125
          z: 45
        '5':
          x: 49
          y: 125
          z: 161
        '6':
          x: 49
          y: 125
          z: 160
        '7':
          x: 174
          y: 125
          z: 160
        '8':
          x: 174
          y: 125
          z: 159
      spawn:
        red:
          x: 76.5
          y: 124
          z: 46.0
        purple:
          x: 201.5
          y: 124
          z: 160.0
        green:
          x: 76.5
          y: 124
          z: 161.0
        cyan:
          x: 201.5
          y: 124
          z: 45.0
        npc:
          update:
            '1':
              x: 203.5
              y: 124.0
              z: 171.5
            '2':
              x: 78.5
              y: 124.0
              z: 172.5
            '3':
              x: 78.5
              y: 124.0
              z: 57.5
            '4':
              x: 203.5
              y: 124.0
              z: 56.5
          sell:
            '1':
              x: 203.5
              y: 124.0
              z: 148.5
            '2':
              x: 78.5
              y: 124.0
              z: 149.5
            '3':
              x: 78.5
              y: 124.0
              z: 34.5
            '4':
              x: 203.5
              y: 124.0
              z: 33.5


more:
  item:
    name:
      glass:
        cyan: Бирюзовая команда
        red: Красная команда
        green: Зеленая команда
        purple: Фиолетовая команда
  price:
    '1': 100
    '2': 300
    '3': 500
    '4': 1000
    '5': 1700
    '6': 2500
    '7': 3500
    '8': 4700
    '9': 6000
    '10': 7500
    '11': 9200
    '12': 11000
    '13': 13000
    '14': 15200
    '15': 17500